name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      run: |
        IMAGE_NAME="ghcr.io/bleumink/matrix-openai-bot"
        docker buildx build \
          --platform linux/amd64 \
          --file Dockerfile \
          --tag $IMAGE_NAME:${{ github.sha }} \
          --tag $IMAGE_NAME:latest \
          --push .
        