name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: register
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build
      run: |
        IMAGE_NAME=ghcr.io/bleumink/matrix-openai-bot
        docker build . \
          --file Dockerfile \
          -t $IMAGE_NAME:${{ github.sha }} \
          -t $IMAGE_NAME:latest

    - name: push
      run: |
        IMAGE_NAME=ghcr.io/bleumink/matrix-openai-bot
        docker push $IMAGE_NAME:${{ github.sha }}
        docker push $IMAGE_NAME:latest
        
